use_frameworks!

def shared_pods
	pod 'MTCircularSlider', :path => '../'
end

target 'MTCircularSlider_Example' do
	shared_pods

  target 'MTCircularSlider_Tests' do
    inherit! :search_paths

		shared_pods
  end
end

post_install do |installer|
	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['SWIFT_VERSION'] = '4.1'
		end
	end
end
