use_frameworks!

target 'MTCircularSlider_Example' do
  pod 'MTCircularSlider', :path => '../'

  target 'MTCircularSlider_Tests' do
    inherit! :search_paths

		pod 'MTCircularSlider', :path => '../'
  end
end
