use_frameworks!

def shared_pods
	pod 'MTCircularSlider', :path => '../'
end

target 'MTCircularSlider_Example' do
	shared_pods

  target 'MTCircularSlider_Tests' do
    inherit! :search_paths

		shared_pods
  end
end
