# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods --pre # Since Travis is not always on latest version
- pod install --project-directory=Example
install:
- ./install_swiftlint.sh
script:
- set -o pipefail && xcodebuild test -workspace Example/MTCircularSlider.xcworkspace -scheme MTCircularSlider-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination "platform=iOS Simulator,OS=11.1,name=iPhone 8" | xcpretty
- pod lib lint --allow-warnings
- swiftlint

